application: ne-track
version: alpha2patch6
runtime: go
api_version: go1

skip_files:
- ^(.*/)?app\.yaml$
- ^(.*/)?app\.yml$
- ^(.*/)?index\.yaml$
- ^(.*/)?index\.yml$
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?development-data.*
- ^(.*/)?.*credentials\..*
- ^(.*/)?.*\.bat$
- ^(.*/)?.*\.sh$
- ^(.*/)?.*\.sublime-
- ^(.*/)?LICENSE$
- ^(.*/)?README\.md$

inbound_services:
- warmup

default_expiration: "364d"

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/favicon\.ico
  http_headers:
    X-Frame-Options: "SAMEORIGIN"
    X-XSS-Protection: "0"
- url: /static/css/(.*)
  static_files: static/css/\1
  upload: static/css/(.*)\.css
  http_headers:
    X-Frame-Options: "SAMEORIGIN"
    X-XSS-Protection: "0"
- url: /static/img/(.*)
  static_files: static/img/\1
  upload: static/img/(.*)\.(png|gif)
  http_headers:
    X-Frame-Options: "SAMEORIGIN"
    X-XSS-Protection: "0"
- url: /static/js/(.*)
  static_files: static/js/\1
  upload: static/js/(.*)\.js
  http_headers:
    X-Frame-Options: "SAMEORIGIN"
    X-XSS-Protection: "0"

- url: /announce
  script: _go_app

- url: /_cron/expire
  script: _go_app
  login: admin

- url: /_ah/warmup
  script: _go_app
  login: admin
- url: /_ah/queue/go/.*
  script: _go_app
  login: admin

- url: /_ah/stats/.*
  script: _go_app
  login: admin